language: php

env:
  global:
    - 'FTP_USER=samsulamin'
    - 'FTP_PASS=samsulamin13'

script:
#scrip buat folder baru
#- "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html/uas'"

#scrip upload file *.php
- "curl -T input.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/uas/"
- "curl -T koneksi.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/uas/"
- "curl -T index.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/uas/"
- "curl -T simpandata.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/uas/"
- "curl -T update.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/uas/"
- "curl -T hapus.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/uas/"
- "curl -T form-edit.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/uas/"

